In [3]:
import string
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [103]:
with open(r'C:\Users\AnjaniK\Desktop\tweets.csv', 'r', newline='', encoding='ISO-8859-1') as csvfile:

    df = pd.read_csv(csvfile)

In [104]:
df.tail()

,Unnamed: 0,text,favorited,favoriteCount,replyToSN,created,truncated,replyToSID,id,replyToUID,statusSource,screenName,retweetCount,isRetweet,retweeted,longitude,latitude
14995,14996,RT @natsdany: First time Last...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828918951937,NaN,"<a href=""http://twitter.com/download/android"" ...",tommysboi,33,True,False,NaN,NaN
14996,14997,RT @MTVNEWS: The #AvengersEndgame cast has see...,False,0,NaN,2019-04-23 09:22:03,False,NaN,1120618828038311936,NaN,"<a href=""http://twitter.com/download/iphone"" r...",kimberleywithae,2307,True,False,NaN,NaN
14997,14998,@SPICinemas kindly announce the approximate ti...,False,0,SPICinemas,2019-04-23 09:22:02,False,NaN,1120618823667920896,919079586.0,"<a href=""http://twitter.com/download/android"" ...",Gnanavel07,0,False,False,NaN,NaN
14998,14999,"RT @Marvel: We salute you, @ChrisEvans! #Capta...",False,0,NaN,2019-04-23 09:22:02,False,NaN,1120618823600803840,NaN,"<a href=""https://mobile.twitter.com"" rel=""nofo...",_moonljght,13167,True,False,NaN,NaN
14999,15000,"RT @Avengers: Welcome to the party, @RobertDow...",False,0,NaN,2019-04-23 09:22:01,False,NaN,1120618822300569601,NaN,"<a href=""http://twitter.com/download/android"" ...",CaterinaCabrel1,10736,True,False,NaN,NaN

In [105]:
df.shape

(15000, 17)

In [106]:
df.columns

Index(['Unnamed: 0', 'text', 'favorited', 'favoriteCount', 'replyToSN',
       'created', 'truncated', 'replyToSID', 'id', 'replyToUID',
       'statusSource', 'screenName', 'retweetCount', 'isRetweet', 'retweeted',
       'longitude', 'latitude'],
      dtype='object')

In [132]:
df_new = df[['created','screenName', 'text']].copy()
df_new.columns = ['Timestamp','Screen_Name', 'Raw_Text']
df_new.head()

,Timestamp,Screen_Name,Raw_Text
0,2019-04-23 10:43:30,DavidAc96,RT @mrvelstan: literally nobody:\r\nme:\r\n\r\...
1,2019-04-23 10:43:30,NRmalaa,"RT @agntecarter: im emotional, sorry!!\r\n\r\..."
2,2019-04-23 10:43:30,jijitsuu,saving these bingo cards for tomorrow \r\n©\r\...
3,2019-04-23 10:43:29,SahapunB,RT @HelloBoon: Man these #AvengersEndgame ads ...
4,2019-04-23 10:43:29,stella22_97,"RT @Marvel: We salute you, @ChrisEvans! #Capta..."

In [133]:
letters_numbers_space = string.ascii_letters + string.digits + '\s'
letters_numbers_space

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\\s'

In [134]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [141]:
import re   #regular expression

def filter_and_tokenize(raw_text):
    
    cleaned_tokenized_text  = re.findall('\w+', raw_text)
    
    #cleaned_tokenized_text = "".join([char.lower() for char in raw_text if char in filter_])
    
    return cleaned_tokenized_text


letters_numbers_space = string.ascii_letters + string.digits + " "
filter_ = '[%s]+' % re.escape(letters_numbers_space)
filtered_text = df_new['Raw_Text'].apply(lambda x: filter_and_tokenize(x.lower()))

df_new['Cleaned_and_Tokenized'] = filtered_text
#df_new=df_new.drop(['Cleaned_Text'],axis=1)
df_new.head()

,Timestamp,Screen_Name,Raw_Text,Cleaned_and_Tokenized
0,2019-04-23 10:43:30,DavidAc96,RT @mrvelstan: literally nobody:\r\nme:\r\n\r\...,"[rt, mrvelstan, literally, nobody, me, avenger..."
1,2019-04-23 10:43:30,NRmalaa,"RT @agntecarter: im emotional, sorry!!\r\n\r\...","[rt, agntecarter, i, m, emotional, sorry, 2014..."
2,2019-04-23 10:43:30,jijitsuu,saving these bingo cards for tomorrow \r\n©\r\...,"[saving, these, bingo, cards, for, tomorrow, a..."
3,2019-04-23 10:43:29,SahapunB,RT @HelloBoon: Man these #AvengersEndgame ads ...,"[rt, helloboon, man, these, avengersendgame, a..."
4,2019-04-23 10:43:29,stella22_97,"RT @Marvel: We salute you, @ChrisEvans! #Capta...","[rt, marvel, we, salute, you, chrisevans, capt..."

In [142]:
#def tokenize_(cleaned_text):
    
#    tokenized_text = re.split('\W+', cleaned_text)
#    return tokenized_text

#df_new['Tokenized_Text'] = df_new['Cleaned_Text'].apply(lambda x: tokenize_(x))

#df_new.head()

In [145]:
from nltk import PorterStemmer 
from nltk.corpus import stopwords

ps = PorterStemmer()
stop_words = stopwords.words('english')

def remove_stop_words(tokenized_text):
    
    no_stop_words = [word for word in tokenized_text if word not in stop_words]
    
    return no_stop_words

df_new['No_Stop_Words'] = df_new['Cleaned_and_Tokenized'].apply(lambda x: remove_stop_words(x))
 

def stemming(tokenized_text):
    
    stemmed_text = [ps.stem(word) for word in tokenized_text]
    
    return stemmed_text

df_new['Stemmed_Text'] = df_new['No_Stop_Words'].apply(lambda x: stemming(x))

df_new.head()

,Timestamp,Screen_Name,Raw_Text,Cleaned_and_Tokenized,No_Stop_Words,Stemmed_Text
0,2019-04-23 10:43:30,DavidAc96,RT @mrvelstan: literally nobody:\r\nme:\r\n\r\...,"[rt, mrvelstan, literally, nobody, me, avenger...","[rt, mrvelstan, literally, nobody, avengersend...","[rt, mrvelstan, liter, nobodi, avengersendgam,..."
1,2019-04-23 10:43:30,NRmalaa,"RT @agntecarter: im emotional, sorry!!\r\n\r\...","[rt, agntecarter, i, m, emotional, sorry, 2014...","[rt, agntecarter, emotional, sorry, 2014, x, 2...","[rt, agntecart, emot, sorri, 2014, x, 2019, bl..."
2,2019-04-23 10:43:30,jijitsuu,saving these bingo cards for tomorrow \r\n©\r\...,"[saving, these, bingo, cards, for, tomorrow, a...","[saving, bingo, cards, tomorrow, avengersendga...","[save, bingo, card, tomorrow, avengersendgam, ..."
3,2019-04-23 10:43:29,SahapunB,RT @HelloBoon: Man these #AvengersEndgame ads ...,"[rt, helloboon, man, these, avengersendgame, a...","[rt, helloboon, man, avengersendgame, ads, eve...","[rt, helloboon, man, avengersendgam, ad, every..."
4,2019-04-23 10:43:29,stella22_97,"RT @Marvel: We salute you, @ChrisEvans! #Capta...","[rt, marvel, we, salute, you, chrisevans, capt...","[rt, marvel, salute, chrisevans, captainameric...","[rt, marvel, salut, chrisevan, captainamerica,..."